version: "3.8"

services:
  # Frontend Service (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Backend Service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./backend/db/database.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
